{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMiuFwhzKirxCRMXYBE3iEs",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/YounSooKimTech/NLP_Repo/blob/main/NER_AppleData_Joy.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Question1"
      ],
      "metadata": {
        "id": "zaL8JoP4YSW8"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 704
        },
        "id": "yRzkYlIYXdRV",
        "outputId": "87cb396d-9dc2-49d6-b594-2c7ac1bf4e5e"
      },
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "                                              thread  \\\n",
              "0  {'uuid': '958670c1717dd8f1edbe33369ee12469c1ca...   \n",
              "1  {'uuid': '4aa124a2c78843f8404405e65cd69da7bfae...   \n",
              "2  {'uuid': '26ebb8ab008ed759d017994376326cc50809...   \n",
              "3  {'uuid': 'cb43510b88a39af756c8744572f3f6e91155...   \n",
              "4  {'uuid': 'cfe464ff046a7ad47b3fd6a13eac8eb7252d...   \n",
              "\n",
              "                                       uuid  \\\n",
              "0  958670c1717dd8f1edbe33369ee12469c1cafdf1   \n",
              "1  4aa124a2c78843f8404405e65cd69da7bfaed9c4   \n",
              "2  26ebb8ab008ed759d017994376326cc508090c07   \n",
              "3  cb43510b88a39af756c8744572f3f6e9115566ce   \n",
              "4  cfe464ff046a7ad47b3fd6a13eac8eb7252d03e6   \n",
              "\n",
              "                                                 url  ord_in_thread  \\\n",
              "0  http://omgili.com/ri/.wHSUbtEfZRyyLJKogCgQjT1s...              0   \n",
              "1  http://omgili.com/ri/.wHSUbtEfZQVWCSCAg0UcdNr5...              0   \n",
              "2  http://omgili.com/ri/.wHSUbtEfZQr3Bw_O2_O6hJpn...              0   \n",
              "3  http://omgili.com/ri/.wHSUbtEfZS9pZjbkz0yttu0H...              0   \n",
              "4  http://omgili.com/ri/.wHSUbtEfZQi9gXn_bDGqQCdG...              0   \n",
              "\n",
              "   parent_url             author                      published  \\\n",
              "0         NaN  Roland Hutchinson  2020-06-03T10:00:00.000+03:00   \n",
              "1         NaN                     2020-06-03T09:58:00.000+03:00   \n",
              "2         NaN                 Ki  2020-06-03T09:52:00.000+03:00   \n",
              "3         NaN      Bradley Prior  2020-06-03T09:41:00.000+03:00   \n",
              "4         NaN                     2020-06-03T09:25:00.000+03:00   \n",
              "\n",
              "                                               title  \\\n",
              "0  New iPad Air may come with USB-C not Lightning...   \n",
              "1  iOS 14 Will Reportedly Support All iPhone Mode...   \n",
              "2  iPhone Looters Being Tracked â€“ Apple Warns Pho...   \n",
              "3         Apple bug exposed user accounts to hackers   \n",
              "4  French govt's StopCovid tracing app debuts on ...   \n",
              "\n",
              "                                                text highlightText  \\\n",
              "0  Apple is expected to launch its fourth generat...                 \n",
              "1  iOS 14 Will Support All iPhone Models That Run...                 \n",
              "2  in: News iPhone Looters Receives Being Tracked...                 \n",
              "3  Bradley Prior 3 June 2020 Subscribe\\nA bug in ...                 \n",
              "4  French govt's StopCovid tracing app debuts on ...                 \n",
              "\n",
              "  highlightTitle highlightThreadTitle language  \\\n",
              "0                                      english   \n",
              "1                                      english   \n",
              "2                                      english   \n",
              "3                                      english   \n",
              "4                                      english   \n",
              "\n",
              "                                      external_links external_images  \\\n",
              "0                                                 []              []   \n",
              "1  [https://www.theverifier.co.il/46415/ios-14-de...              []   \n",
              "2  [https://www.twitter.com/onlyfanobtainer/statu...              []   \n",
              "3  [https://bhavukjain.com/blog/2020/05/30/zeroda...              []   \n",
              "4                                                 []              []   \n",
              "\n",
              "                                            entities  rating  \\\n",
              "0  {'persons': [{'name': 'mac otakara', 'sentimen...     NaN   \n",
              "1  {'persons': [{'name': 'jagmeet singh', 'sentim...     NaN   \n",
              "2  {'persons': [{'name': 'george floyd', 'sentime...     NaN   \n",
              "3  {'persons': [{'name': 'bhavuk jain', 'sentimen...     NaN   \n",
              "4  {'persons': [{'name': 'telecompaper', 'sentime...     NaN   \n",
              "\n",
              "                         crawled  \n",
              "0  2020-06-03T10:10:13.000+03:00  \n",
              "1  2020-06-03T10:07:59.021+03:00  \n",
              "2  2020-06-03T09:55:17.014+03:00  \n",
              "3  2020-06-03T09:45:27.024+03:00  \n",
              "4  2020-06-03T09:30:58.008+03:00  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-437fec9a-89fa-470b-b793-8fd069683634\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>thread</th>\n",
              "      <th>uuid</th>\n",
              "      <th>url</th>\n",
              "      <th>ord_in_thread</th>\n",
              "      <th>parent_url</th>\n",
              "      <th>author</th>\n",
              "      <th>published</th>\n",
              "      <th>title</th>\n",
              "      <th>text</th>\n",
              "      <th>highlightText</th>\n",
              "      <th>highlightTitle</th>\n",
              "      <th>highlightThreadTitle</th>\n",
              "      <th>language</th>\n",
              "      <th>external_links</th>\n",
              "      <th>external_images</th>\n",
              "      <th>entities</th>\n",
              "      <th>rating</th>\n",
              "      <th>crawled</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>{'uuid': '958670c1717dd8f1edbe33369ee12469c1ca...</td>\n",
              "      <td>958670c1717dd8f1edbe33369ee12469c1cafdf1</td>\n",
              "      <td>http://omgili.com/ri/.wHSUbtEfZRyyLJKogCgQjT1s...</td>\n",
              "      <td>0</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Roland Hutchinson</td>\n",
              "      <td>2020-06-03T10:00:00.000+03:00</td>\n",
              "      <td>New iPad Air may come with USB-C not Lightning...</td>\n",
              "      <td>Apple is expected to launch its fourth generat...</td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td>english</td>\n",
              "      <td>[]</td>\n",
              "      <td>[]</td>\n",
              "      <td>{'persons': [{'name': 'mac otakara', 'sentimen...</td>\n",
              "      <td>NaN</td>\n",
              "      <td>2020-06-03T10:10:13.000+03:00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>{'uuid': '4aa124a2c78843f8404405e65cd69da7bfae...</td>\n",
              "      <td>4aa124a2c78843f8404405e65cd69da7bfaed9c4</td>\n",
              "      <td>http://omgili.com/ri/.wHSUbtEfZQVWCSCAg0UcdNr5...</td>\n",
              "      <td>0</td>\n",
              "      <td>NaN</td>\n",
              "      <td></td>\n",
              "      <td>2020-06-03T09:58:00.000+03:00</td>\n",
              "      <td>iOS 14 Will Reportedly Support All iPhone Mode...</td>\n",
              "      <td>iOS 14 Will Support All iPhone Models That Run...</td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td>english</td>\n",
              "      <td>[https://www.theverifier.co.il/46415/ios-14-de...</td>\n",
              "      <td>[]</td>\n",
              "      <td>{'persons': [{'name': 'jagmeet singh', 'sentim...</td>\n",
              "      <td>NaN</td>\n",
              "      <td>2020-06-03T10:07:59.021+03:00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>{'uuid': '26ebb8ab008ed759d017994376326cc50809...</td>\n",
              "      <td>26ebb8ab008ed759d017994376326cc508090c07</td>\n",
              "      <td>http://omgili.com/ri/.wHSUbtEfZQr3Bw_O2_O6hJpn...</td>\n",
              "      <td>0</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Ki</td>\n",
              "      <td>2020-06-03T09:52:00.000+03:00</td>\n",
              "      <td>iPhone Looters Being Tracked â€“ Apple Warns Pho...</td>\n",
              "      <td>in: News iPhone Looters Receives Being Tracked...</td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td>english</td>\n",
              "      <td>[https://www.twitter.com/onlyfanobtainer/statu...</td>\n",
              "      <td>[]</td>\n",
              "      <td>{'persons': [{'name': 'george floyd', 'sentime...</td>\n",
              "      <td>NaN</td>\n",
              "      <td>2020-06-03T09:55:17.014+03:00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>{'uuid': 'cb43510b88a39af756c8744572f3f6e91155...</td>\n",
              "      <td>cb43510b88a39af756c8744572f3f6e9115566ce</td>\n",
              "      <td>http://omgili.com/ri/.wHSUbtEfZS9pZjbkz0yttu0H...</td>\n",
              "      <td>0</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Bradley Prior</td>\n",
              "      <td>2020-06-03T09:41:00.000+03:00</td>\n",
              "      <td>Apple bug exposed user accounts to hackers</td>\n",
              "      <td>Bradley Prior 3 June 2020 Subscribe\\nA bug in ...</td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td>english</td>\n",
              "      <td>[https://bhavukjain.com/blog/2020/05/30/zeroda...</td>\n",
              "      <td>[]</td>\n",
              "      <td>{'persons': [{'name': 'bhavuk jain', 'sentimen...</td>\n",
              "      <td>NaN</td>\n",
              "      <td>2020-06-03T09:45:27.024+03:00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>{'uuid': 'cfe464ff046a7ad47b3fd6a13eac8eb7252d...</td>\n",
              "      <td>cfe464ff046a7ad47b3fd6a13eac8eb7252d03e6</td>\n",
              "      <td>http://omgili.com/ri/.wHSUbtEfZQi9gXn_bDGqQCdG...</td>\n",
              "      <td>0</td>\n",
              "      <td>NaN</td>\n",
              "      <td></td>\n",
              "      <td>2020-06-03T09:25:00.000+03:00</td>\n",
              "      <td>French govt's StopCovid tracing app debuts on ...</td>\n",
              "      <td>French govt's StopCovid tracing app debuts on ...</td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td></td>\n",
              "      <td>english</td>\n",
              "      <td>[]</td>\n",
              "      <td>[]</td>\n",
              "      <td>{'persons': [{'name': 'telecompaper', 'sentime...</td>\n",
              "      <td>NaN</td>\n",
              "      <td>2020-06-03T09:30:58.008+03:00</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-437fec9a-89fa-470b-b793-8fd069683634')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-437fec9a-89fa-470b-b793-8fd069683634 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-437fec9a-89fa-470b-b793-8fd069683634');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 4
        }
      ],
      "source": [
        "import pandas as pd\n",
        "\n",
        "apple = pd.read_json('/content/webhose_apple.json', lines=True)\n",
        "apple.head()"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "apple0 = apple[\"text\"][0]\n",
        "print(apple0)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Ehu48s2VXvNA",
        "outputId": "8210a047-89ee-4bda-8278-d753e9f0188a"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Apple is expected to launch its fourth generation iPad Air some time this year or early next year and according to a recent report, Apple with switch to USB-C on the next generation model.\n",
            "The current model comes with a lightning port, the current iPad Pro uses USB-C, Apple switched its iPad Pro models to this back in 2018.\n",
            "The news of the switch comes in a report from Mac Otakara who have revealed that the new model iPad Air will be based on the 11 inch iPad pro and will come with USB-C.\n",
            "As well as USB-C the device may get a number of other upgrades including a mini-LED display, although Apple are not expected to launch their new devices with mini-LED and microLED displays until 2021.\n",
            "It is possible that we could hear about this new iPad in September along with the new iPhone 12 handsets, although we may have tom wait until next year to see the device.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import spacy\n",
        "\n",
        "nlp = spacy.load(\"en_core_web_sm\")\n",
        "\n",
        "doc = nlp(apple0)\n",
        "\n",
        "for ent in doc.ents:\n",
        "  print(ent.text, ent.label_)\n",
        "\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "eG2rnDPhX4to",
        "outputId": "2ba76013-e3a2-40f2-bfdd-e9276981e59e"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Apple ORG\n",
            "fourth ORDINAL\n",
            "iPad Air ORG\n",
            "this year DATE\n",
            "early next year DATE\n",
            "Apple ORG\n",
            "iPad ORG\n",
            "Apple ORG\n",
            "iPad ORG\n",
            "2018 DATE\n",
            "Mac Otakara PERSON\n",
            "iPad Air ORG\n",
            "11 inch QUANTITY\n",
            "iPad ORG\n",
            "Apple ORG\n",
            "2021 DATE\n",
            "iPad ORG\n",
            "September DATE\n",
            "12 CARDINAL\n",
            "next year DATE\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from spacy import displacy\n",
        "\n",
        "displacy.render(doc, style=\"ent\", jupyter=True)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 227
        },
        "id": "4C8TFsTfYEgH",
        "outputId": "381afac8-26f0-4b3f-b35b-a4b855b20c1c"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "<span class=\"tex2jax_ignore\"><div class=\"entities\" style=\"line-height: 2.5; direction: ltr\">\n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Apple\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " is expected to launch its \n",
              "<mark class=\"entity\" style=\"background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    fourth\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORDINAL</span>\n",
              "</mark>\n",
              " generation \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    iPad Air\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " some time \n",
              "<mark class=\"entity\" style=\"background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    this year\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">DATE</span>\n",
              "</mark>\n",
              " or \n",
              "<mark class=\"entity\" style=\"background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    early next year\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">DATE</span>\n",
              "</mark>\n",
              " and according to a recent report, \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Apple\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " with switch to USB-C on the next generation model.</br>The current model comes with a lightning port, the current \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    iPad\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " Pro uses USB-C, \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Apple\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " switched its \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    iPad\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " Pro models to this back in \n",
              "<mark class=\"entity\" style=\"background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    2018\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">DATE</span>\n",
              "</mark>\n",
              ".</br>The news of the switch comes in a report from \n",
              "<mark class=\"entity\" style=\"background: #aa9cfc; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Mac Otakara\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">PERSON</span>\n",
              "</mark>\n",
              " who have revealed that the new model \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    iPad Air\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " will be based on the \n",
              "<mark class=\"entity\" style=\"background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    11 inch\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">QUANTITY</span>\n",
              "</mark>\n",
              " \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    iPad\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " pro and will come with USB-C.</br>As well as USB-C the device may get a number of other upgrades including a mini-LED display, although \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Apple\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " are not expected to launch their new devices with mini-LED and microLED displays until \n",
              "<mark class=\"entity\" style=\"background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    2021\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">DATE</span>\n",
              "</mark>\n",
              ".</br>It is possible that we could hear about this new \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    iPad\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " in \n",
              "<mark class=\"entity\" style=\"background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    September\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">DATE</span>\n",
              "</mark>\n",
              " along with the new iPhone \n",
              "<mark class=\"entity\" style=\"background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    12\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">CARDINAL</span>\n",
              "</mark>\n",
              " handsets, although we may have tom wait until \n",
              "<mark class=\"entity\" style=\"background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    next year\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">DATE</span>\n",
              "</mark>\n",
              " to see the device.</div></span>"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "lXhWxFraYQut"
      },
      "execution_count": 5,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Question 3"
      ],
      "metadata": {
        "id": "iviSQhUoYURm"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "apple0 = apple[\"text\"][0]\n",
        "\n",
        "sents = apple[\"text\"][0].split(\".\")\n",
        "\n",
        "print(sents[0], len(sents))"
      ],
      "metadata": {
        "id": "QkafmCNZcNcU",
        "outputId": "18104105-a4dd-44f3-85d6-554e73c02280",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Apple is expected to launch its fourth generation iPad Air some time this year or early next year and according to a recent report, Apple with switch to USB-C on the next generation model 6\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import re\n",
        "\n",
        "for i in range(6):\n",
        "  print(\"sentence\", i, re.search(\"Apple\", sents[i]))\n",
        "  print(\"sentence\", i, re.search(\"\\d{4}\", sents[i]))\n",
        "\n",
        "sents"
      ],
      "metadata": {
        "id": "zNZ32-A2cgTA",
        "outputId": "bc1b3a9d-d860-4e0f-b7f0-78cdb69273fd",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "sentence 0 <re.Match object; span=(0, 5), match='Apple'>\n",
            "sentence 0 None\n",
            "sentence 1 <re.Match object; span=(81, 86), match='Apple'>\n",
            "sentence 1 <re.Match object; span=(132, 136), match='2018'>\n",
            "sentence 2 None\n",
            "sentence 2 None\n",
            "sentence 3 <re.Match object; span=(103, 108), match='Apple'>\n",
            "sentence 3 <re.Match object; span=(196, 200), match='2021'>\n",
            "sentence 4 None\n",
            "sentence 4 None\n",
            "sentence 5 None\n",
            "sentence 5 None\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "['Apple is expected to launch its fourth generation iPad Air some time this year or early next year and according to a recent report, Apple with switch to USB-C on the next generation model',\n",
              " '\\nThe current model comes with a lightning port, the current iPad Pro uses USB-C, Apple switched its iPad Pro models to this back in 2018',\n",
              " '\\nThe news of the switch comes in a report from Mac Otakara who have revealed that the new model iPad Air will be based on the 11 inch iPad pro and will come with USB-C',\n",
              " '\\nAs well as USB-C the device may get a number of other upgrades including a mini-LED display, although Apple are not expected to launch their new devices with mini-LED and microLED displays until 2021',\n",
              " '\\nIt is possible that we could hear about this new iPad in September along with the new iPhone 12 handsets, although we may have tom wait until next year to see the device',\n",
              " '']"
            ]
          },
          "metadata": {},
          "execution_count": 13
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import spacy\n",
        "\n",
        "nlp = spacy.blank(\"en\")\n",
        "\n",
        "ner = nlp.add_pipe(\"ner\")\n",
        "\n",
        "TRAIN_DATA = [\n",
        "    (sents[0], {'entities': [(0, 5, \"ORG\")]}), \n",
        "    (sents[1], {'entities': [(81, 36, \"ORG\")]}),\n",
        "    (sents[3], {'entities': [(103, 108, \"ORG\")]}),\n",
        "    (sents[1], {'entities': [(132, 136, \"DATE\")]}), \n",
        "    (sents[3], {'entities': [(196,200, \"DATE\")]})\n",
        "    ]"
      ],
      "metadata": {
        "id": "Z25HC5WSc8cv"
      },
      "execution_count": 14,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "#ner = nlp.add_pipe('ner', last=True)\n",
        "#nlp.analyze_pipes()['summary']\n",
        "\n",
        "for _, annotations in TRAIN_DATA:\n",
        "    for ent in annotations.get(\"entities\"):\n",
        "        ner.add_label(ent[2])\n",
        "\n",
        "from spacy.training import Example\n",
        "\n",
        "n_iter = 50\n",
        "loss_history=[]\n",
        "with nlp.select_pipes(enable=[\"ner\"]):\n",
        "    optimizer = nlp.begin_training()\n",
        "    for itn in range(n_iter):\n",
        "        losses = {}\n",
        "        texts, annotations = zip(*TRAIN_DATA)\n",
        "        example = []\n",
        "        for i in range(len(texts)):\n",
        "            doc = nlp.make_doc(texts[i])\n",
        "            example.append(Example.from_dict(doc, annotations[i]))\n",
        "        nlp.update(example, drop=0.5, losses=losses, sgd=optimizer)\n",
        "        loss_history.append(losses['ner'])"
      ],
      "metadata": {
        "id": "-nGnqT8BaeIK"
      },
      "execution_count": 15,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from spacy import displacy\n",
        "\n",
        "doc = nlp(apple0)\n",
        "displacy.render(doc, style=\"ent\", jupyter=True)"
      ],
      "metadata": {
        "id": "jCVHFCjMdyPi",
        "outputId": "0ca390ab-c047-486c-e73f-30e58082cac9",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 192
        }
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "<span class=\"tex2jax_ignore\"><div class=\"entities\" style=\"line-height: 2.5; direction: ltr\">\n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Apple\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " is expected to launch its fourth generation iPad Air some time this year or early next year and according to a recent report, Apple with switch to USB-C on the next generation model.</br>The current model comes with a lightning port, the current iPad Pro uses USB-C, Apple switched its iPad Pro models to this back in 2018.</br>The news of the switch comes in a report from Mac Otakara who have revealed that the new model iPad Air will be based on the 11 inch iPad pro and will come with USB-C.</br>As well as USB-C the device may get a number of other upgrades including a mini-LED display, although \n",
              "<mark class=\"entity\" style=\"background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Apple\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">ORG</span>\n",
              "</mark>\n",
              " are not expected to launch their new devices with mini-LED and microLED displays until 2021.</br>It is possible that we could hear about this new iPad in September along with the new iPhone 12 handsets, although we may have tom wait until next year to see the device.</div></span>"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Question 3 with spacy.tokens Span"
      ],
      "metadata": {
        "id": "v5ppwyoOQzUC"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# call the data frame\n",
        "import pandas as pd\n",
        "\n",
        "df = pd.read_json(\"/content/webhose_apple.json\", lines=True)\n",
        "apple7 = df[\"text\"][7]\n",
        "print(apple7)\n"
      ],
      "metadata": {
        "id": "Ls0AosOcQ05h",
        "outputId": "fe63f806-f53c-41e0-a55c-cfe51cfe5991",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 72,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Mr. Ranjeet Sundher reports\n",
            "60% OF GLOBAL COBALT SUPPLY AT RISK AS DRC CRACKDOWN INTENSIFIES\n",
            "Bolt Metals Corp. has noted the Financial Times reported that Huayou Cobalt, \"China's top cobalt producer, halts buying from Congo miners.\" It's widely reported that the Democratic Republic of Congo (the \"DRC\") represents 60% of global cobalt production.\n",
            "Shanghai-listed Huayou supplies cobalt to battery makers LG Chem of South Korea and CATL of China, as well as Chinese carmaker BYD and Germany's Volkswagen.\n",
            "Bowing to international pressure to shutter its conflict-sourced cobalt, Huayou is the latest conglomerate to exit the DRC, joining Apple, Google and several auto manufacturers. Huayou is looking to raise $870m in an effort to expand nickel and cobalt sulphate production in Indonesia. Huayou's plant in Indonesia's Morowali Industrial Park is expected to produce at least 60,000 tonnes of nickel content per year within 2 years.\n",
            "Ranjeet Sundher, CEO of Bolt Metals, comments, \"Cobalt remains an important ingredient in battery chemistries, and international markets are increasingly demanding conflict-free sources for the metal. Bolt Metals believes Indonesia represents a unique opportunity to exploit cobalt as a byproduct of the countries abundant nickel resources. Our flagship Cyclops nickel-cobalt asset has demonstrated strong results from 2018-19 drilling and benchmark analysis, providing an essential foundation for the eventual development of a pilot plant.\"\n",
            "Recent positive developments within Indonesia's mining sector have generated significant interest in Bolt Metals and its Cyclops project from downstream battery metal suppliers within Indonesia as well as China, the largest battery metals market in the world.\n",
            "Bolt Metals has signed preliminary offtake agreements with Beijing Easpring, China's top battery metals supplier (please refer to the Company's press release issued July 11, 2018) and Junan Jinxin (please refer to the Company's press release issued March 5, 2020), primarily engaged in the acquisition, production, processing and marketing of tungsten and cobalt 1 . Both agreements provide a strategic investment option. Bolt Metals is working toward signing definitive agreements with both companies, while preparing for the commencement of construction of a pilot plant in Canada.\n",
            "Processing results from the pilot plant will be used to establish design criteria for the subsequent demonstration plant in Indonesia, which will produce nickel and cobalt products suitable to meet market specifications. As well as demonstrating Bolt Metal's ability to produce a product within market specifications, the demonstration plant will be used to establish design criteria for a commercial full-scale plant.\n",
            "1 The Company has not made a decision to proceed to production and would not do so without first establishing mineral reserves.\n",
            "About Bolt Metals\n",
            "BOLT Metals is a Canadian-based exploration company focused on the acquisition and development of production grade nickel and cobalt deposits, key raw material inputs for the growing lithium-ion battery industry.\n",
            "We seek Safe Harbor.\n",
            " \n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# blank spacy\n",
        "\n",
        "import spacy\n",
        "\n",
        "nlp = spacy.blank(\"en\")\n",
        "doc = nlp(apple7)\n",
        "\n",
        "for token in doc[:10]:\n",
        "  print(token)"
      ],
      "metadata": {
        "id": "dw9pRPdxQ9bg",
        "outputId": "586acdd2-4cfa-4688-9451-e71cd19ce372",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 73,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Mr.\n",
            "Ranjeet\n",
            "Sundher\n",
            "reports\n",
            "\n",
            "\n",
            "60\n",
            "%\n",
            "OF\n",
            "GLOBAL\n",
            "COBALT\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# add pipe line\n",
        "\n",
        "nlp.add_pipe(\"ner\")\n",
        "nlp.begin_training()\n",
        "\n",
        "nlp.pipe_names"
      ],
      "metadata": {
        "id": "sxLqYEpKRLew",
        "outputId": "f2941347-d019-4fba-8fcd-aa293e3e0be8",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 74,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "['ner']"
            ]
          },
          "metadata": {},
          "execution_count": 74
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import re\n",
        "\n",
        "doc = nlp(apple7)\n",
        "\n",
        "for token in doc:\n",
        "  if token.text == \"Ranjeet\":\n",
        "    print(token.text, token.i)\n",
        "  if token.text == \"Bolt\":\n",
        "    print(token.text, token.i)\n",
        "\n"
      ],
      "metadata": {
        "id": "Py687YcCRUTH",
        "outputId": "ce7cb455-e5e6-4c3b-b233-da4033a515b6",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 78,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Ranjeet 1\n",
            "Bolt 18\n",
            "Ranjeet 180\n",
            "Bolt 185\n",
            "Bolt 214\n",
            "Bolt 283\n",
            "Bolt 311\n",
            "Bolt 387\n",
            "Bolt 452\n",
            "Bolt 508\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from spacy.tokens import Span\n",
        "\n",
        "doc = nlp(apple7)\n",
        "\n",
        "s1 = Span(doc, 1, 3, label=\"PERSON\")\n",
        "s2 = Span(doc, 180, 182, label=\"PERSON\")\n",
        "s3 = Span(doc, 185, 187, label=\"CORP\")\n",
        "s4 = Span(doc, 214, 216, label=\"CORP\")\n",
        "s5 = Span(doc, 283, 285, label=\"CORP\")\n",
        "s6 = Span(doc, 311, 313, label=\"CORP\")\n",
        "s7 = Span(doc, 387, 389, label=\"CORP\")\n",
        "s8 = Span(doc, 452, 454, label=\"CORP\")\n",
        "s9 = Span(doc, 508, 510, label=\"CORP\")\n",
        "\n",
        "doc.set_ents([s1, s2, s3, s4, s5, s6, s7, s8, s9], default=\"unmodified\")\n",
        "\n",
        "for ent in doc.ents:\n",
        "  print(ent.text, ent.label_)"
      ],
      "metadata": {
        "id": "-PtdOg_YSkRr",
        "outputId": "4a45f6d2-81b9-4de0-d2f3-76e2b1f9fcc7",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 79,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Ranjeet Sundher PERSON\n",
            "Ranjeet Sundher PERSON\n",
            "Bolt Metals CORP\n",
            "Bolt Metals CORP\n",
            "Bolt Metals CORP\n",
            "Bolt Metals CORP\n",
            "Bolt Metals CORP\n",
            "Bolt Metal CORP\n",
            "Bolt Metals CORP\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from spacy import displacy\n",
        "\n",
        "displacy.render(doc, style=\"ent\", jupyter=True)"
      ],
      "metadata": {
        "id": "kg32edsnT7EO",
        "outputId": "9512c233-17af-4e93-a76f-7d9cc5b28492",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 772
        }
      },
      "execution_count": 80,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "<span class=\"tex2jax_ignore\"><div class=\"entities\" style=\"line-height: 2.5; direction: ltr\">Mr. \n",
              "<mark class=\"entity\" style=\"background: #aa9cfc; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Ranjeet Sundher\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">PERSON</span>\n",
              "</mark>\n",
              " reports</br>60% OF GLOBAL COBALT SUPPLY AT RISK AS DRC CRACKDOWN INTENSIFIES</br>Bolt Metals Corp. has noted the Financial Times reported that Huayou Cobalt, &quot;China's top cobalt producer, halts buying from Congo miners.&quot; It's widely reported that the Democratic Republic of Congo (the &quot;DRC&quot;) represents 60% of global cobalt production.</br>Shanghai-listed Huayou supplies cobalt to battery makers LG Chem of South Korea and CATL of China, as well as Chinese carmaker BYD and Germany's Volkswagen.</br>Bowing to international pressure to shutter its conflict-sourced cobalt, Huayou is the latest conglomerate to exit the DRC, joining Apple, Google and several auto manufacturers. Huayou is looking to raise $870m in an effort to expand nickel and cobalt sulphate production in Indonesia. Huayou's plant in Indonesia's Morowali Industrial Park is expected to produce at least 60,000 tonnes of nickel content per year within 2 years.</br>\n",
              "<mark class=\"entity\" style=\"background: #aa9cfc; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Ranjeet Sundher\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">PERSON</span>\n",
              "</mark>\n",
              ", CEO of \n",
              "<mark class=\"entity\" style=\"background: #ddd; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Bolt Metals\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">CORP</span>\n",
              "</mark>\n",
              ", comments, &quot;Cobalt remains an important ingredient in battery chemistries, and international markets are increasingly demanding conflict-free sources for the metal. \n",
              "<mark class=\"entity\" style=\"background: #ddd; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Bolt Metals\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">CORP</span>\n",
              "</mark>\n",
              " believes Indonesia represents a unique opportunity to exploit cobalt as a byproduct of the countries abundant nickel resources. Our flagship Cyclops nickel-cobalt asset has demonstrated strong results from 2018-19 drilling and benchmark analysis, providing an essential foundation for the eventual development of a pilot plant.&quot;</br>Recent positive developments within Indonesia's mining sector have generated significant interest in \n",
              "<mark class=\"entity\" style=\"background: #ddd; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Bolt Metals\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">CORP</span>\n",
              "</mark>\n",
              " and its Cyclops project from downstream battery metal suppliers within Indonesia as well as China, the largest battery metals market in the world.</br>\n",
              "<mark class=\"entity\" style=\"background: #ddd; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Bolt Metals\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">CORP</span>\n",
              "</mark>\n",
              " has signed preliminary offtake agreements with Beijing Easpring, China's top battery metals supplier (please refer to the Company's press release issued July 11, 2018) and Junan Jinxin (please refer to the Company's press release issued March 5, 2020), primarily engaged in the acquisition, production, processing and marketing of tungsten and cobalt 1 . Both agreements provide a strategic investment option. \n",
              "<mark class=\"entity\" style=\"background: #ddd; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Bolt Metals\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">CORP</span>\n",
              "</mark>\n",
              " is working toward signing definitive agreements with both companies, while preparing for the commencement of construction of a pilot plant in Canada.</br>Processing results from the pilot plant will be used to establish design criteria for the subsequent demonstration plant in Indonesia, which will produce nickel and cobalt products suitable to meet market specifications. As well as demonstrating \n",
              "<mark class=\"entity\" style=\"background: #ddd; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Bolt Metal\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">CORP</span>\n",
              "</mark>\n",
              "'s ability to produce a product within market specifications, the demonstration plant will be used to establish design criteria for a commercial full-scale plant.</br>1 The Company has not made a decision to proceed to production and would not do so without first establishing mineral reserves.</br>About \n",
              "<mark class=\"entity\" style=\"background: #ddd; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
              "    Bolt Metals\n",
              "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem\">CORP</span>\n",
              "</mark>\n",
              "</br>BOLT Metals is a Canadian-based exploration company focused on the acquisition and development of production grade nickel and cobalt deposits, key raw material inputs for the growing lithium-ion battery industry.</br>We seek Safe Harbor.</br> </div></span>"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Question 2"
      ],
      "metadata": {
        "id": "WMuTG6jyhP2S"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install google-cloud-language==2.6"
      ],
      "metadata": {
        "id": "tiA1Lj1ikYX1",
        "outputId": "ab679c50-dbca-40a7-a579-4cb78019b2e6",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        }
      },
      "execution_count": 81,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n",
            "Collecting google-cloud-language==2.6\n",
            "  Downloading google_cloud_language-2.6.0-py2.py3-none-any.whl (84 kB)\n",
            "\u001b[K     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 84 kB 2.2 MB/s \n",
            "\u001b[?25hRequirement already satisfied: protobuf<5.0.0dev,>=3.20.2 in /usr/local/lib/python3.7/dist-packages (from google-cloud-language==2.6) (3.20.3)\n",
            "Collecting proto-plus<2.0.0dev,>=1.22.0\n",
            "  Downloading proto_plus-1.22.1-py3-none-any.whl (47 kB)\n",
            "\u001b[K     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 47 kB 4.7 MB/s \n",
            "\u001b[?25hCollecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0\n",
            "  Downloading google_api_core-2.10.2-py3-none-any.whl (115 kB)\n",
            "\u001b[K     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 115 kB 28.0 MB/s \n",
            "\u001b[?25hRequirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (2.23.0)\n",
            "Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (1.35.0)\n",
            "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (1.56.4)\n",
            "Collecting grpcio-status<2.0dev,>=1.33.2\n",
            "  Downloading grpcio_status-1.49.1-py3-none-any.whl (14 kB)\n",
            "Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (1.49.1)\n",
            "Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (1.15.0)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (4.9)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (0.2.8)\n",
            "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (4.2.4)\n",
            "Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (57.4.0)\n",
            "Collecting protobuf<5.0.0dev,>=3.20.2\n",
            "  Downloading protobuf-4.21.7-cp37-abi3-manylinux2014_x86_64.whl (408 kB)\n",
            "\u001b[K     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 408 kB 46.0 MB/s \n",
            "\u001b[?25hRequirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (0.4.8)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (2.10)\n",
            "Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (3.0.4)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (1.24.3)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-language==2.6) (2022.9.24)\n",
            "Installing collected packages: protobuf, grpcio-status, google-api-core, proto-plus, google-cloud-language\n",
            "  Attempting uninstall: protobuf\n",
            "    Found existing installation: protobuf 3.20.3\n",
            "    Uninstalling protobuf-3.20.3:\n",
            "      Successfully uninstalled protobuf-3.20.3\n",
            "  Attempting uninstall: google-api-core\n",
            "    Found existing installation: google-api-core 1.31.6\n",
            "    Uninstalling google-api-core-1.31.6:\n",
            "      Successfully uninstalled google-api-core-1.31.6\n",
            "  Attempting uninstall: google-cloud-language\n",
            "    Found existing installation: google-cloud-language 1.2.0\n",
            "    Uninstalling google-cloud-language-1.2.0:\n",
            "      Successfully uninstalled google-cloud-language-1.2.0\n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "tensorflow 2.9.2 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.7 which is incompatible.\n",
            "tensorflow-metadata 1.10.0 requires protobuf<4,>=3.13, but you have protobuf 4.21.7 which is incompatible.\n",
            "tensorboard 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.7 which is incompatible.\n",
            "google-cloud-translate 1.5.0 requires google-api-core[grpc]<2.0.0dev,>=1.6.0, but you have google-api-core 2.10.2 which is incompatible.\n",
            "google-cloud-firestore 1.7.0 requires google-api-core[grpc]<2.0.0dev,>=1.14.0, but you have google-api-core 2.10.2 which is incompatible.\n",
            "google-cloud-datastore 1.8.0 requires google-api-core[grpc]<2.0.0dev,>=1.6.0, but you have google-api-core 2.10.2 which is incompatible.\n",
            "google-cloud-core 1.0.3 requires google-api-core<2.0.0dev,>=1.14.0, but you have google-api-core 2.10.2 which is incompatible.\n",
            "google-cloud-bigquery-storage 1.1.2 requires protobuf<4.0.0dev, but you have protobuf 4.21.7 which is incompatible.\n",
            "firebase-admin 4.4.0 requires google-api-core[grpc]<2.0.0dev,>=1.14.0; platform_python_implementation != \"PyPy\", but you have google-api-core 2.10.2 which is incompatible.\u001b[0m\n",
            "Successfully installed google-api-core-2.10.2 google-cloud-language-2.6.0 grpcio-status-1.49.1 proto-plus-1.22.1 protobuf-4.21.7\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "application/vnd.colab-display-data+json": {
              "pip_warning": {
                "packages": [
                  "google"
                ]
              }
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.cloud import language_v1\n",
        "\n",
        "def sample_analyze_entities(text_content):\n",
        "    \"\"\"\n",
        "    Analyzing Entities in a String\n",
        "\n",
        "    Args:\n",
        "      text_content The text content to analyze\n",
        "    \"\"\"\n",
        "\n",
        "    client = language_v1.LanguageServiceClient()\n",
        "\n",
        "    # text_content = 'California is a state.'\n",
        "\n",
        "    # Available types: PLAIN_TEXT, HTML\n",
        "    type = language_v1.types.Document.Type.PLAIN_TEXT\n",
        "\n",
        "    # Optional. If not specified, the language is automatically detected.\n",
        "    # For list of supported languages:\n",
        "    # https://cloud.google.com/natural-language/docs/languages\n",
        "    language = \"en\"\n",
        "    document = {\"content\": text_content, \"type_\": type, \"language\": language}\n",
        "\n",
        "    # Available values: NONE, UTF8, UTF16, UTF32\n",
        "    # encoding_type = language_v1.EncodingType.UTF8\n",
        "\n",
        "    response = client.analyze_entities(request = {'document': document, 'encoding_type': \"UTF8\"})\n",
        "    return response \n",
        "\n",
        "\"\"\"\n",
        "    # Loop through entitites returned from the API\n",
        "    for entity in response.entities:\n",
        "        print(u\"Representative name for the entity: {}\".format(entity.name))\n",
        "\n",
        "        # Get entity type, e.g. PERSON, LOCATION, ADDRESS, NUMBER, et al\n",
        "        print(u\"Entity type: {}\".format(language_v1.Entity.Type(entity.type_).name))\n",
        "\n",
        "        # Get the salience score associated with the entity in the [0, 1.0] range\n",
        "        print(u\"Salience score: {}\".format(entity.salience))\n",
        "\n",
        "        # Loop over the metadata associated with entity. For many known entities,\n",
        "        # the metadata is a Wikipedia URL (wikipedia_url) and Knowledge Graph MID (mid).\n",
        "        # Some entity types may have additional metadata, e.g. ADDRESS entities\n",
        "        # may have metadata for the address street_name, postal_code, et al.\n",
        "        for metadata_name, metadata_value in entity.metadata.items():\n",
        "            print(u\"{}: {}\".format(metadata_name, metadata_value))\n",
        "\n",
        "        # Loop over the mentions of this entity in the input document.\n",
        "        # The API currently supports proper noun mentions.\n",
        "        for mention in entity.mentions:\n",
        "            print(u\"Mention text: {}\".format(mention.text.content))\n",
        "\n",
        "            # Get the mention type, e.g. PROPER for proper noun\n",
        "            print(\n",
        "                u\"Mention type: {}\".format(language_v1.EntityMention.Type(mention.type_).name)\n",
        "            )\n",
        "\n",
        "    # Get the language of the text, which will be the same as\n",
        "    # the language specified in the request or, if not specified,\n",
        "    # the automatically-detected language.\n",
        "    \n",
        "    print(u\"Language of the text: {}\".format(response.language))\n",
        "    \"\"\"\n"
      ],
      "metadata": {
        "id": "-hfWkEI4geQC",
        "outputId": "60d8aef2-5502-4566-8abb-9c33726f3ba5",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 128
        }
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "'\\n    # Loop through entitites returned from the API\\n    for entity in response.entities:\\n        print(u\"Representative name for the entity: {}\".format(entity.name))\\n\\n        # Get entity type, e.g. PERSON, LOCATION, ADDRESS, NUMBER, et al\\n        print(u\"Entity type: {}\".format(language_v1.Entity.Type(entity.type_).name))\\n\\n        # Get the salience score associated with the entity in the [0, 1.0] range\\n        print(u\"Salience score: {}\".format(entity.salience))\\n\\n        # Loop over the metadata associated with entity. For many known entities,\\n        # the metadata is a Wikipedia URL (wikipedia_url) and Knowledge Graph MID (mid).\\n        # Some entity types may have additional metadata, e.g. ADDRESS entities\\n        # may have metadata for the address street_name, postal_code, et al.\\n        for metadata_name, metadata_value in entity.metadata.items():\\n            print(u\"{}: {}\".format(metadata_name, metadata_value))\\n\\n        # Loop over the mentions of this entity in the input document.\\n        # The API currently supports proper noun mentions.\\n        for mention in entity.mentions:\\n            print(u\"Mention text: {}\".format(mention.text.content))\\n\\n            # Get the mention type, e.g. PROPER for proper noun\\n            print(\\n                u\"Mention type: {}\".format(language_v1.EntityMention.Type(mention.type_).name)\\n            )\\n\\n    # Get the language of the text, which will be the same as\\n    # the language specified in the request or, if not specified,\\n    # the automatically-detected language.\\n    \\n    print(u\"Language of the text: {}\".format(response.language))\\n    '"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "string"
            }
          },
          "metadata": {},
          "execution_count": 2
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "sample_analyze_entities(apple0)"
      ],
      "metadata": {
        "id": "4MQ0S4D6gi0g",
        "outputId": "73943148-2da2-47f4-8309-b932c520d7f5",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12fd4550>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12fd4550>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c4a590>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c4a590>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c4c250>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c4c250>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c56f50>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c56f50>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c57f50>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c57f50>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c68ed0>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c68ed0>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bf7f90>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bf7f90>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bf7e50>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bf7e50>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c0ec50>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c0ec50>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c13d50>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c13d50>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bf9d90>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bf9d90>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12ca5850>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12ca5850>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c51890>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c51890>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c21f50>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c21f50>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c62090>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c62090>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c03ed0>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c03ed0>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c57f90>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c57f90>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c2f8d0>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c2f8d0>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c68510>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12c68510>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bc2150>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bc2150>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bc53d0>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bc53d0>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bf7510>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bf7510>)\n",
            "ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fea12c9d550>\" raised exception!\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 111, in refresh\n",
            "    self._retrieve_info(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 88, in _retrieve_info\n",
            "    request, service_account=self._service_account_email\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 234, in get_service_account_info\n",
            "    return get(request, path, params={\"recursive\": \"true\"})\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/_metadata.py\", line 187, in get\n",
            "    response,\n",
            "google.auth.exceptions.TransportError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bd6f50>)\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/grpc/_plugin_wrapping.py\", line 90, in __call__\n",
            "    context, _AuthMetadataPluginCallback(callback_state, callback))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 101, in __call__\n",
            "    callback(self._get_authorization_headers(context), None)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/transport/grpc.py\", line 88, in _get_authorization_headers\n",
            "    self._request, context.method_name, context.service_url, headers\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py\", line 133, in before_request\n",
            "    self.refresh(request)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py\", line 117, in refresh\n",
            "    six.raise_from(new_exc, caught_exc)\n",
            "  File \"<string>\", line 3, in raise_from\n",
            "google.auth.exceptions.RefreshError: (\"Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\\nb''\", <google.auth.transport.requests._Response object at 0x7fea12bd6f50>)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.cloud import language_v1\n",
        "\n",
        "client = language_v1.LanguageServiceClient()\n",
        "\n",
        "document = language_v1.Document(\n",
        "    content=text, type_=language_v1.Document.Type.PLAIN_TEXT\n",
        ")\n",
        "\n",
        "encoding_type = language_v1.EncodingType.UTF8\n",
        "\n",
        "response = client.analyze_entities(request = {'document': document, 'encoding_type': encoding_type})\n"
      ],
      "metadata": {
        "id": "x4sRiduBhx7X",
        "outputId": "c916e97c-0f9c-405f-b38b-90a95a79256c",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 245
        }
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "error",
          "ename": "NameError",
          "evalue": "ignored",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-1-d1907aee4615>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m document = language_v1.Document(\n\u001b[0;32m----> 6\u001b[0;31m     \u001b[0mcontent\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mtext\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtype_\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlanguage_v1\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mDocument\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mType\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPLAIN_TEXT\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m )\n\u001b[1;32m      8\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mNameError\u001b[0m: name 'text' is not defined"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "M6FjWXYijjRr"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "y7-m7JLrhhP-"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from google.cloud import language_v1\n",
        "\n",
        "client = language_v1.LanguageServiceClient()\n",
        "text_content = text\n",
        "type_ = language_v1.Document.Type.PLAIN_TEXT\n",
        "language = \"en\"\n",
        "document = {\"content\": text_content, \"type_\": type_, \"language\": language}\n",
        "encoding_type = language_v1.EncodingType.UTF8\n",
        "response = client.analyze_entities(request = {'document': document, 'encoding_type': encoding_type})\n"
      ],
      "metadata": {
        "id": "Q7k-OqANgGUm"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# key = AIzaSyBKRopWE9A-CsN9pBAb3u-KcaDebwyVOOk"
      ],
      "metadata": {
        "id": "U_m9KHmYqi3q"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import google.auth\n",
        "import googleapiclient.discovery\n",
        "\n",
        "\n",
        "def quickstart(project_id, member):\n",
        "    \"\"\"Gets a policy, adds a member, prints their permissions, and removes the member.\"\"\"\n",
        "\n",
        "    # Role to be granted.\n",
        "    role = \"roles/logging.logWriter\"\n",
        "\n",
        "    # Initializes service.\n",
        "    crm_service = initialize_service()\n",
        "\n",
        "    # Grants your member the 'Log Writer' role for the project.\n",
        "    modify_policy_add_role(crm_service, project_id, role, member)\n",
        "\n",
        "    # Gets the project's policy and prints all members with the 'Log Writer' role.\n",
        "    policy = get_policy(crm_service, project_id)\n",
        "    binding = next(b for b in policy[\"bindings\"] if b[\"role\"] == role)\n",
        "    print(f'Role: {(binding[\"role\"])}')\n",
        "    print(\"Members: \")\n",
        "    for m in binding[\"members\"]:\n",
        "        print(f\"[{m}]\")\n",
        "\n",
        "    # Removes the member from the 'Log Writer' role.\n",
        "    modify_policy_remove_member(crm_service, project_id, role, member)\n",
        "\n",
        "\n",
        "def initialize_service():\n",
        "    \"\"\"Initializes a Cloud Resource Manager service.\"\"\"\n",
        "\n",
        "    credentials, _ = google.auth.default(\n",
        "        scopes=[\"https://www.googleapis.com/auth/cloud-platform\"]\n",
        "    )\n",
        "    crm_service = googleapiclient.discovery.build(\n",
        "        \"cloudresourcemanager\", \"v1\", credentials=credentials\n",
        "    )\n",
        "    return crm_service\n",
        "\n",
        "\n",
        "def modify_policy_add_role(crm_service, project_id, role, member):\n",
        "    \"\"\"Adds a new role binding to a policy.\"\"\"\n",
        "\n",
        "    policy = get_policy(crm_service, project_id)\n",
        "\n",
        "    binding = None\n",
        "    for b in policy[\"bindings\"]:\n",
        "        if b[\"role\"] == role:\n",
        "            binding = b\n",
        "            break\n",
        "    if binding is not None:\n",
        "        binding[\"members\"].append(member)\n",
        "    else:\n",
        "        binding = {\"role\": role, \"members\": [member]}\n",
        "        policy[\"bindings\"].append(binding)\n",
        "\n",
        "    set_policy(crm_service, project_id, policy)\n",
        "\n",
        "\n",
        "def modify_policy_remove_member(crm_service, project_id, role, member):\n",
        "    \"\"\"Removes a  member from a role binding.\"\"\"\n",
        "\n",
        "    policy = get_policy(crm_service, project_id)\n",
        "\n",
        "    binding = next(b for b in policy[\"bindings\"] if b[\"role\"] == role)\n",
        "    if \"members\" in binding and member in binding[\"members\"]:\n",
        "        binding[\"members\"].remove(member)\n",
        "\n",
        "    set_policy(crm_service, project_id, policy)\n",
        "\n",
        "\n",
        "def get_policy(crm_service, project_id, version=3):\n",
        "    \"\"\"Gets IAM policy for a project.\"\"\"\n",
        "\n",
        "    policy = (\n",
        "        crm_service.projects()\n",
        "        .getIamPolicy(\n",
        "            resource=project_id,\n",
        "            body={\"options\": {\"requestedPolicyVersion\": version}},\n",
        "        )\n",
        "        .execute()\n",
        "    )\n",
        "    return policy\n",
        "\n",
        "\n",
        "def set_policy(crm_service, project_id, policy):\n",
        "    \"\"\"Sets IAM policy for a project.\"\"\"\n",
        "\n",
        "    policy = (\n",
        "        crm_service.projects()\n",
        "        .setIamPolicy(resource=project_id, body={\"policy\": policy})\n",
        "        .execute()\n",
        "    )\n",
        "    return policy\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    # TODO: replace with your project ID\n",
        "    project_id = \"your-project-id\"\n",
        "    # TODO: Replace with the ID of your member in the form 'user:member@example.com'.\n",
        "    member = \"your-member\"\n",
        "    quickstart(project_id, member)"
      ],
      "metadata": {
        "id": "064kMR2Xu4yE"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "pip install --upgrade google-api-python-client google-auth google-auth-httplib2"
      ],
      "metadata": {
        "id": "g2q0IhpGuusQ"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "gcloud config set project PROJECT_ID"
      ],
      "metadata": {
        "id": "PWW-a2jyufq4"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "\n",
        "from google.oauth2 import service_account\n",
        "import googleapiclient.discovery\n",
        "\n",
        "def create_key(service_account_email):\n",
        "    \"\"\"Creates a key for a service account.\"\"\"\n",
        "\n",
        "    credentials = service_account.Credentials.from_service_account_file(\n",
        "        filename=os.environ['GOOGLE_APPLICATION_CREDENTIALS'],\n",
        "        scopes=['https://www.googleapis.com/auth/cloud-platform'])\n",
        "\n",
        "    service = googleapiclient.discovery.build(\n",
        "        'iam', 'v1', credentials=credentials)\n",
        "\n",
        "    key = service.projects().serviceAccounts().keys().create(\n",
        "        name='projects/-/serviceAccounts/' + service_account_email, body={}\n",
        "        ).execute()\n",
        "\n",
        "    # The privateKeyData field contains the base64-encoded service account key\n",
        "    # in JSON format.\n",
        "    # TODO(Developer): Save the below key {json_key_file} to a secure location.\n",
        "    #  You cannot download it again later.\n",
        "    # import base64\n",
        "    # json_key_file = base64.b64decode(key['privateKeyData']).decode('utf-8')\n",
        "\n",
        "    if not key['disabled']:\n",
        "        print('Created json key')"
      ],
      "metadata": {
        "id": "bVITpm1_t454"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "Yuxytk9it6Gg"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Imports the Google Cloud client library\n",
        "from google.cloud import language_v1\n",
        "\n",
        "# Instantiates a client\n",
        "client = language_v1.LanguageServiceClient()\n",
        "\n",
        "# The text to analyze\n",
        "text = \"Hello, world!\"\n",
        "document = language_v1.Document(\n",
        "    content=text, type_=language_v1.Document.Type.PLAIN_TEXT\n",
        ")\n",
        "\n",
        "# Detects the sentiment of the text\n",
        "sentiment = client.analyze_sentiment(\n",
        "    request={\"document\": document}\n",
        ").document_sentiment\n",
        "\n",
        "print(\"Text: {}\".format(text))\n",
        "print(\"Sentiment: {}, {}\".format(sentiment.score, sentiment.magnitude))"
      ],
      "metadata": {
        "id": "EJ3vYjRSnh6B"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from google.cloud import language_v1\n",
        "\n",
        "def sample_analyze_entities(text_content):\n",
        "    \"\"\"\n",
        "    Analyzing Entities in a String\n",
        "\n",
        "    Args:\n",
        "      text_content The text content to analyze\n",
        "    \"\"\"\n",
        "\n",
        "    client = language_v1.LanguageServiceClient()\n",
        "\n",
        "    text_content = 'California is a state.'\n",
        "\n",
        "    # Available types: PLAIN_TEXT, HTML\n",
        "    type_ = language_v1.Document.Type.PLAIN_TEXT\n",
        "\n",
        "    # Optional. If not specified, the language is automatically detected.\n",
        "    # For list of supported languages:\n",
        "    # https://cloud.google.com/natural-language/docs/languages\n",
        "    language = \"en\"\n",
        "    document = {\"content\": text_content, \"type_\": type_, \"language\": language}\n",
        "\n",
        "    # Available values: NONE, UTF8, UTF16, UTF32\n",
        "    encoding_type = language_v1.EncodingType.UTF8\n",
        "\n",
        "    response = client.analyze_entities(request = {'document': document, 'encoding_type': encoding_type})\n",
        "\n",
        "    # Loop through entitites returned from the API\n",
        "    for entity in response.entities:\n",
        "        print(u\"Representative name for the entity: {}\".format(entity.name))\n",
        "\n",
        "        # Get entity type, e.g. PERSON, LOCATION, ADDRESS, NUMBER, et al\n",
        "        print(u\"Entity type: {}\".format(language_v1.Entity.Type(entity.type_).name))\n",
        "\n",
        "        # Get the salience score associated with the entity in the [0, 1.0] range\n",
        "        print(u\"Salience score: {}\".format(entity.salience))\n",
        "\n",
        "        # Loop over the metadata associated with entity. For many known entities,\n",
        "        # the metadata is a Wikipedia URL (wikipedia_url) and Knowledge Graph MID (mid).\n",
        "        # Some entity types may have additional metadata, e.g. ADDRESS entities\n",
        "        # may have metadata for the address street_name, postal_code, et al.\n",
        "        for metadata_name, metadata_value in entity.metadata.items():\n",
        "            print(u\"{}: {}\".format(metadata_name, metadata_value))\n",
        "\n",
        "        # Loop over the mentions of this entity in the input document.\n",
        "        # The API currently supports proper noun mentions.\n",
        "        for mention in entity.mentions:\n",
        "            print(u\"Mention text: {}\".format(mention.text.content))\n",
        "\n",
        "            # Get the mention type, e.g. PROPER for proper noun\n",
        "            print(\n",
        "                u\"Mention type: {}\".format(language_v1.EntityMention.Type(mention.type_).name)\n",
        "            )\n",
        "\n",
        "    # Get the language of the text, which will be the same as\n",
        "    # the language specified in the request or, if not specified,\n",
        "    # the automatically-detected language.\n",
        "    print(u\"Language of the text: {}\".format(response.language))\n"
      ],
      "metadata": {
        "id": "9C8-01dAiwQ6"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "sample_analyze_entities(\"California is a state\")"
      ],
      "metadata": {
        "id": "iH24z1oNhROR"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "pip install protobuf==3.20.*"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 345
        },
        "id": "d8j4HL6kkghG",
        "outputId": "a76a4bd7-fe8e-4d12-af49-cfd245f22de0"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n",
            "Collecting protobuf==3.20.*\n",
            "  Downloading protobuf-3.20.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)\n",
            "\u001b[K     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1.0 MB 5.1 MB/s \n",
            "\u001b[?25hInstalling collected packages: protobuf\n",
            "  Attempting uninstall: protobuf\n",
            "    Found existing installation: protobuf 3.17.3\n",
            "    Uninstalling protobuf-3.17.3:\n",
            "      Successfully uninstalled protobuf-3.17.3\n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "tensorflow 2.9.2 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.\n",
            "tensorboard 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.\u001b[0m\n",
            "Successfully installed protobuf-3.20.3\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "application/vnd.colab-display-data+json": {
              "pip_warning": {
                "packages": [
                  "google"
                ]
              }
            }
          },
          "metadata": {}
        }
      ]
    }
  ]
}